### PR TITLE
Martys backup

### PR DESCRIPTION
**Pull request by sylink**
Magerun pull-request check-list:

- [* ] Pull request against develop branch (if not, just close and create a new one against it)
- [* ] README.md reflects changes (if any)

Subject: Create backup command

Fixes: None really, just a new command.

Changes proposed in this pull request:

I've added a simple command I had for n98-magerun for Magento 1 that created a backup of an entire Magento web root. Very simple. Not sure if it needs more options, I can think of some but would not use them myself!

### CODE REVIEW

**Comment by sylink** [comment]
The built-in can be unreliable, there are a couple bugs with it. Though its not nearly as bad as Magento 1's backup utility was. 

If its not desired thats ok, I can just make it a module for myself :)

**Comment by hostep** [comment]
@sylink: if you know about bugs in the `setup:backup` command, I'd advise you to either create an issue or a pull request with fixes at the [magento2](https://github.com/magento/magento2) repo, that's probably more efficient and will help all users of Magento 2 and not only the n98/magerun2 users.

I know there are already some fixes in the pipeline for that command:
- not disabling maintenance mode if it was enabled before creating a backup (https://github.com/magento/magento2/pull/11056/commits/2cccbe41cf3ec33d429218cde345fcff42d72344)
- including mysql triggers in the database dump (https://github.com/magento/magento2/pull/11369)
- ...

**Comment by cmuench** [comment]
@sylink Thanks for you submission, but I think like @hostep. We should try to improve the build-in feature. We should not double already existing features.

**Comment by cmuench** [comment]
I will close this PR. We can discuss this topic here, but the current PR is not valid anymore.

**Pull request closed without merging**
