### PR TITLE
Fix code generator command after upgrade to Magento 2.2

### PR DESCRIPTION
**Pull request by cmuench**
Magerun pull-request check-list:

- [X] Pull request against develop branch (if not, just close and create a new one against it)
- [X] README.md reflects changes (if any)

Code generator has minor changes in Magento 2.2. The extended class is not longer created relative class namespace. We have to define the full namespace.

Changes proposed in this pull request:

Add full namespace for extended class.

### CODE REVIEW

**Comment by ktomk** [comment]
I have not yet found out the original reason why this (#315) happened, perhaps some code-changes in the source files w/ Magento 2.2 (but no reasoning yet).

**Comment by cmuench** [comment]
It could be related to changes in `Zend\Code` components.
https://github.com/zendframework/zend-code/issues/117

**Comment by cmuench** [comment]
I already started a test with a version compare. My goal is that the fixture must not be changed at the end. Currently I have to fight with Phpunit. Hope I will get it read the next days.

**Comment by ktomk** [comment]
I think we can trust that library, so should only check the Magerun command more or less generally works (runs) and then a quick check on the string result that is more stable (e.g. expected minimum string length or some regex pattern).

In case we find bugs, we could add regression tests for specific cases.

**Comment by cmuench** [comment]
I have already a plan to add a version_compare with a parameter toggle. Next week I am in vacation. Maybe I have time to fix the problem.

**Comment by cmuench** [comment]
Painfully the build is broken at the moment. We could skip the tests for 2.2 at the moment.

**Comment by ktomk** [comment]
For the moment, skipping sounds fair. That at least could restore the build. Or just check for string to be returned / file created (?). Would be a valid test in my eyes and could spare the skipping.

**Pull request merged**
