### PR TITLE
Set forceUseDb option to type VALUE_NONE

### PR DESCRIPTION
**Pull request by jalogut**
Magerun pull-request check-list:

- [ ] Pull request against develop branch (if not, just close and create a new one against it)
- [ ] README.md reflects changes (if any)

Subject: (50 characters or less)

Fixes # .

Changes proposed in this pull request:

- ...

- ...

- ...

### CODE REVIEW

**Comment by ktomk** [comment]
@jalogut: Due to too haste commits the develop branch was actually not green any longer. I've reverted these commits. Please rebase your changes on top of 9534d3f0524088ad5120f39657513a06f7ba31cc and force push to this PR. This should show if it applies green or not. Sorry for that.

And a short description for the PR is welcome, too. You can remove the checklist etc. as this is exemplary only and your PR is rather small so I guess it does not need a large description, just a little background for the change (e.g. command didn't run when giving that parameter).

**Comment by tkn98** [comment]
We believe that the bug reported is fixed in the development version. It can be upgraded to it using the `self-update` command with the `--unstable` switch.

**Comment by tkn98** [comment]
@jalogut  You can find the changes in https://github.com/netz98/n98-magerun2/commit/8b994568e60d0248f5249fe971a5f5cbc16d5522, we cherry picked them just in case you wonder.

**Comment by jalogut** [comment]
@tkn98 thanks for merging. Sorry that I did not have time this week to add the changes you mentioned.

**Comment by ktomk** [comment]
@jalogut no problem, this was rather trivial, sorry for asking that much (it's my other account I use at work). Thanks for bringing up the issue despite little time.

**Pull request closed without merging**
