### PR TITLE
[Feature] #56: add customer:delete command

### LINKED ISSUE #56: Porting command: customer:delete
Delete Customer/s

### PR DESCRIPTION
**Pull request by mautz-et-tong**
Magerun pull-request check-list:

- [x] Pull request against develop branch (if not, just close and create a new one against it)
- [x] README.md reflects changes (if any)

Subject: add customer:delete command

Fixes #56

Changes proposed in this pull request:

- add customer:delete command
- add fuzziness to delete process (delete customer where email like "%email%")

# TEST SAMPLES:

## MASS DELETE
```
./n98-magerun2.phar customer:create foo@example.com passworD123 John Doe base taxvat DE12345678 prefix Mrs.
Customer foo@example.com successfully created
./n98-magerun2.phar customer:create foo@test-example.com passworD123 John Doe base taxvat DE12345678 prefix Mrs.
Customer foo@test-example.com successfully created
./n98-magerun2.phar customer:list
+-------+-----------+----------+----------------------+---------+---------------------+
| id    | firstname | lastname | email                | website | created_at          |
+-------+-----------+----------+----------------------+---------+---------------------+
| 10080 | John      | Doe      | foo@example.com      | 1       | 2022-01-10 16:10:03 |
| 10081 | John      | Doe      | foo@test-example.com | 1       | 2022-01-10 16:10:36 |
+-------+-----------+----------+----------------------+---------+---------------------+
./n98-magerun2.phar customer:delete --all
Delete more than 1 customer? y
Delete all customers?: y
Are you sure? [n]: y
Successfully deleted 2 customer/s
./n98-magerun2.phar customer:list
No customers found
./n98-magerun2.phar customer:create foo@test-example.com passworD123 John Doe base taxvat DE12345678 prefix Mrs.
Customer foo@test-example.com successfully created
./n98-magerun2.phar customer:create bar@test-example.com passworD123 John Doe base taxvat DE12345678 prefix Mrs.
Customer bar@test-example.com successfully created
./n98-magerun2.phar customer:list
+-------+-----------+----------+----------------------+---------+---------------------+
| id    | firstname | lastname | email                | website | created_at          |
+-------+-----------+----------+----------------------+---------+---------------------+
| 10082 | John      | Doe      | foo@test-example.com | 1       | 2022-01-10 16:12:01 |
| 10083 | John      | Doe      | bar@test-example.com | 1       | 2022-01-10 16:12:38 |
+-------+-----------+----------+----------------------+---------+---------------------+
./n98-magerun2.phar customer:delete --fuzzy=FUZZY --email=foo 
Are you sure? [n]: y
Successfully deleted 1 customer/s
./n98-magerun2.phar customer:list
+-------+-----------+----------+----------------------+---------+---------------------+
| id    | firstname | lastname | email                | website | created_at          |
+-------+-----------+----------+----------------------+---------+---------------------+
| 10083 | John      | Doe      | bar@test-example.com | 1       | 2022-01-10 16:12:38 |
+-------+-----------+----------+----------------------+---------+---------------------+
./n98-magerun2.phar customer:create foo@test-example.com passworD123 John Doe base taxvat DE12345678 prefix Mrs.
Customer foo@test-example.com successfully created
./n98-magerun2.phar customer:list
+-------+-----------+----------+----------------------+---------+---------------------+
| id    | firstname | lastname | email                | website | created_at          |
+-------+-----------+----------+----------------------+---------+---------------------+
| 10083 | John      | Doe      | bar@test-example.com | 1       | 2022-01-10 16:12:38 |
| 10084 | John      | Doe      | foo@test-example.com | 1       | 2022-01-10 16:13:38 |
+-------+-----------+----------+----------------------+---------+---------------------+
./n98-magerun2.phar customer:delete --fuzzy=FUZZY --email=test
Are you sure? [n]: y
Successfully deleted 2 customer/s
./n98-magerun2.phar customer:list
No customers found
```

## ID DELETE
```
./n98-magerun2.phar customer:list
No customers found
./n98-magerun2.phar customer:create foo@test-example.com passworD123 John Doe base taxvat DE12345678 prefix Mrs.
Customer foo@test-example.com successfully created
./n98-magerun2.phar customer:list
+-------+-----------+----------+----------------------+---------+---------------------+
| id    | firstname | lastname | email                | website | created_at          |
+-------+-----------+----------+----------------------+---------+---------------------+
| 10085 | John      | Doe      | foo@test-example.com | 1       | 2022-01-10 16:22:05 |
+-------+-----------+----------+----------------------+---------+---------------------+
./n98-magerun2.phar customer:delete --id=10085
Are you sure? [n]: y
./n98-magerun2.phar customer:list
No customers found
```

### CODE REVIEW

**Comment by mautz-et-tong** [comment]
ToDo:
- add tests as this command is destructive

**Comment by mautz-et-tong** [comment]
@cmuench added test to phar-test as requested

**Comment by cmuench** [comment]
@mautz-et-tong thanks for the contribution.

**Comment by sebastian-ehrling** [comment]
when will this feature be available? :) @cmuench

**Comment by cmuench** [comment]
@sebastian-ehrling If you need that, update with `self-update --unstable`.
The next release is really huge and contains the PHP 8.1 support. We plan to release it close to the Magento 2.4.4 update on 2022-04-12.

**Pull request merged**
