### PR TITLE
Bash autocompletion fix for 2.0.0+

### PR DESCRIPTION
**Pull request by Floddy**
This fixes autocompletion in 2.0.0+ for the changed config: commands.

### CODE REVIEW

**Comment by cmuench** [comment]
Thanks

**Comment by ktomk** [comment]
Any reason why not just use `bin/compile-bash-autocompletion` to generate that file?

**Comment by cmuench** [comment]
@ktomk I missed that generator. Should we include it in the build process?

**Comment by ktomk** [comment]
It think it should go into Travis and if there is a diff between the generated and the checked-out one, that job fails. This keeps PRs with new features aligned (or keeps track of changes in the generation which do happen IIRC), so this is not always a build failure, so the Travis job should allow to fail.

**Comment by dvershinin** [comment]
Guys, that updated autocompletion file causes error displayed if bash is used:

```bash: compdef: command not found```

All due to the following line (note that ```compdef``` is not available in bash):

    compdef _n98-magerun2 n98-magerun2.phar n98-magerun2 magerun2

**Comment by ktomk** [comment]
Can you open a new Terminal window with Bash and see whether you're still getting the same error? Or is it just because of having opened Zsh in the same window previously?

Which shell are you using and in which version?

**Comment by ktomk** [comment]
And please create a new issue, no need to hang on some other ticket that is unrelated to the error message you report.

**Comment by dvershinin** [comment]
Sure. See #331. Not using zsh at all. Using bash.

**Pull request merged**
