### PR TITLE
1015 script

### PR DESCRIPTION
**Pull request by amenk**

### CODE REVIEW

**Comment by amenk** [comment]
other tests are failing, do not think they are related to this MR?

**Comment by ktomk** [comment]
No this is a problem with the check actions on github (which is displayed here in the pr), the workflow should be fine, but I need to verify.

You need this in fast? @amenk

**Comment by amenk** [comment]
The quicker, the better, but not crucial :-)
Background: We wanted to optimize lots of single magerun2 config:store:set calls into one script call to improve speed on our CI

**Comment by ktomk** [comment]
merged @amenk , build is also fixed so next PR should not show this check issue (which turned out was actually an incompatibility on PHP 8.1 with latest unstable Magento2-CE).

Thanks!

**Pull request merged**
