### PR TITLE
Script command compatible with Magento 2.1

### PR DESCRIPTION
**Pull request by p-makowski**
Changes proposed in this pull request:

- ScriptCommand compatible with Magento 2.1 with backwards compatibility preserved

### CODE REVIEW

**Comment by tkn98** [comment]
Is this for #212?

**Comment by p-makowski** [comment]
I am sorry - I forgot to link it with issue. 
You are right - it is for #212.

**Comment by tkn98** [comment]
No problem. Just catching up here.

**Comment by tkn98** [comment]
Thanks a lot for the PR, I could now find some time to review it. It generally looks good.

Can you fetch the latest version of the development branch and rebase your two commits on top of it (instead of having a merge commit in the middle that is unrelated to the PR)?

You can then force-push. This should trigger the build on travis again which is also something that would help me for the build problem.

----

Just a marker to myself, and perhaps you've got feedback on it:

> $magentoEdition = 'Community'; // @TODO Replace this if EE is available

This *old* line with TODO, maybe the change for 2.1 is also a fix for the edition earlier?

**Comment by tkn98** [comment]
@p-makowski: I now merged this manually into develop. 

Commits are:

- b387a7c [BUGFIX] Fixed script command to be compatible with Magento 2.1
- 8f495c8 [BUGFIX] Fixed help description of "system:setup:compare-versions"

**Comment by p-makowski** [comment]
I created a new PR with code refactored. 
See https://github.com/netz98/n98-magerun2/pull/215

**Comment by ktomk** [comment]
@p-makowski worte:

I do not know what is exact reason, but on one of mine servers with Mage 2.1 I am getting this error message for n98-magerun2  1.1.15:

> PHP Fatal error:  Uncaught Error: Undefined class constant 'VERSION' in phar:///usr/local/bin/n98-magerun2.phar/src/N98/Magento/Command/ScriptCommand.php:287

I completely do not understand how this happened, but when I extract phar file I see that a new code is not in there. Any ideas why?

**Comment by ktomk** [comment]
Correct, the build of Magent 1.1.15 is broken. The development build does have it.

	wget https://files.magerun.net/n98-magerun2-dev.phar
	md5sum n98-magerun2-dev.phar
	phar extract -f n98-magerun2-dev.phar -i \\/ScriptCommand.php out
	grep -i defined out/src/N98/Magento/Command/ScriptCommand.php


	wget https://files.magerun.net/n98-magerun2.phar
	md5sum n98-magerun2.phar
	phar extract -f n98-magerun2.phar -i \\/ScriptCommand.php out
	grep -i defined out/src/N98/Magento/Command/ScriptCommand.php

I will bump the release, maybe it helps.

**Comment by ktomk** [comment]
You should see this fixed in 1.1.16 md5 3f53675eaa89b7c5064689388fc27efb, at least that one ships with the code.

**Pull request closed without merging**
