### PR TITLE
Fixed running cronjobs configured in database, scheduled imports for example

### PR DESCRIPTION
**Pull request by jspoe**
Magerun pull-request check-list:

- [V] Pull request against develop branch (if not, just close and create a new one against it)
- [ /] README.md reflects changes (if any)

Subject: Fixed a little flaw in sys:cron:run
Changes proposed in this pull request:

- Had a little flaw where a job without a name still could not run, the parentheses we're not correct positioned against the isset($job['name'])

### CODE REVIEW

**Comment by cmuench** [comment]
@jspoe Thanks for your PR. Is it possible that you rebase your changes to one commit?

**Comment by ktomk** [comment]
@jspoe: You don't have to close. Just rebase your branch on develop. Then squash the commits. Then force push to Github, this will update the PR.

If you need more help with the git commands just let us know.

**Comment by jspoe** [comment]
Yes if you would like to provide some commands, then please. Squashing the commit's doesn't seem to change anything else I already had.

**Comment by ktomk** [comment]
Okay, I see. So first of all checkout your feature branch as that is the one to create the pull request from:

     $ git checkout  develop

The other steps depend a bit on how you named the remote of the upstream repository (the netz98/n98-magerun2 one). By convention it is often named `upstream`  (where you have yours as `origin`), but this can vary.  In case you don't have it yet as remote, just add it:

    $ git remote add upstream git@github.com:netz98/n98-magerun2.git

This will add the upstream repository as remote under the name "upstream" to your lokal repository. You can't push to it, but you can fetch/pull from it.

For the following I assume it is named "upstream", change as you see fit if you already configured the remote with a different name.

So as develop branch in the upstream repository has changed already (since the time you forked from it), let's make it fresh and ensure your local develop is fresh:

     $ git fetch upstream develop

And then

     $ git rebase upstream/develop

This should work straight forward. If not, this means that your local develop branch already diverged from upstream. You then need to resolve that conflict first:

     $ git checkout -b develop-mine

Creates a new branch from current state. This preserves the history of "your" develop branch under that new branch name "develop-changed"

    $ git checkout develop

Checkout the "original" develop again.

    $ git reset --hard upstream/develop

Resets the local "develop" branch (the branch currently checked out) to the version of "upstream/develop". That is the revision just fetched from the upstream Magerun2 remote repository.

Now your local develop branch is at the latest revision from upstream. You can then check out your develop version again:

    $ git checkout develop-changed

And then rebase it on top of the develop branch:

    $ git rebase develop

This *should* work flawlessly (I haven't tested it with your revision, but I'm pretty confident as git is pretty well with that). 

Git will then put your changes on top of the changes from the (updated) develop branch. If you now force-push your feature branch to remote (your Github repo) as develop, this pull request here will be automatically updated.  It then should contain only the commits with new (your) changes:

    $ git push origin HEAD:develop -f

So far the theory. You could try this and we then should see the outcome here. It will not yet squash the commits, but we can see if the duplicated-looking-commits disappear (which should bring this pull request one step further and should reduce your pull requests commits).

If not this might be that you created a parallel history as you somewhat merged in upstream commits into your "feature" branch named develop and git on it's own was not able to deal with it.

That is no problem at all in itself, but needs "manual conflict resolution".

There are many ways possible to do that, one quite verbatim way which is perhaps easy to follow is to cherry-pick the commits you want into "develop" and then push it again (with force `-f`) to Github. This will update this pull-request and we can see the outcome. It still won't do the squashing, but I would leave the squashing to another time so that you have the base-history with your PR aligned first as the current line-up of commits above look quite intermixed of two histories (you re-committed upstream commits, this should just not be the case for a pull request).

I hope this is so far easy to follow. If you have any questions or any issues, just comment. If you find this all to complicated, and you perhaps prefer to open a new PR instead, you can do so as well, we can cross-link it. Just write what you see fit.

**Pull request closed without merging**
