### PR TITLE
Added downloads: CE 2.1.12, 2.1.13, 2.2.3 & 2.2.4

### PR DESCRIPTION
**Pull request by mystix**

### CODE REVIEW

**Comment by cmuench** [comment]
Thx

**Comment by ktomk** [comment]
@shinesoftware: Please try the development version of magerun, I think it's not yet in the stable release.

**Comment by shinesoftware** [comment]
@ktomk Where is the .phar file in the dev version?

**Comment by mystix** [comment]
If you need to remain on the stable version, just add this to your `~/.n98-magerun2.yaml` config while waiting for the next release of n98-magerun2:
```
commands:
  N98\Magento\Command\Installer\InstallCommand:
    magento-packages:
      - name: magento-ce-2.2.4
        package: magento/project-community-edition
        version: 2.2.4
        options:
          prefer-dist: true 
          stability: alpha
          repository-url: https://repo.magento.com
      - name: magento-ce-2.2.3
        package: magento/project-community-edition
        version: 2.2.3
        options:
          prefer-dist: true 
          stability: alpha
          repository-url: https://repo.magento.com
      - name: magento-ce-2.1.13
        package: magento/project-community-edition
        version: 2.1.13
        options:
          prefer-dist: true 
          stability: alpha
          repository-url: https://repo.magento.com
      - name: magento-ce-2.1.12
        package: magento/project-community-edition
        version: 2.1.12
        options:
          prefer-dist: true 
          stability: alpha
          repository-url: https://repo.magento.com
```

**Pull request merged**
