### PR TITLE
Add Homebrew installation

### PR DESCRIPTION
**Pull request by mgeoffray**
Magerun pull-request check-list:

- [v ] Pull request against develop branch (if not, just close and create a new one against it)
- [v ] README.md reflects changes (if any)

Subject: (50 characters or less)

Fixes # .

Changes proposed in this pull request:

- Add Homebrew installation

### CODE REVIEW

**Comment by tkn98** [comment]
@mgeoffray: Please squash your commits into one for this feature, thanks as well for taking care!

**Comment by mgeoffray** [comment]
Hi @tkn98 
OK I will make this change during the day. Thank you.

**Comment by mgeoffray** [comment]
@tkn98 squashing is done, I have just pushed. Please notice that the PR on homebrew-php are not accepted yet.

**Comment by mgeoffray** [comment]
Hi,
n98-magerun 2 now is officialy available from homebrew https://github.com/Homebrew/homebrew-php/blob/master/Formula/n98-magerun2.rb

**Comment by ktomk** [comment]
@mgeoffray: Merci beaucoup M.!

In Magerun2 the autocomplete is a bit behind (will catch up sooner or later), does homebrew support (bash) autocompletion? If so it might be worth to take a peek in the autocomplete folders:

* Magerun 1: https://github.com/netz98/n98-magerun/tree/develop/autocompletion
* Magerun 2: https://github.com/netz98/n98-magerun2/tree/develop/autocompletion

The homebrew package is perhaps a good place for such integrations (I personally don't really know, so just a suggestion).

Thanks again for all your efforts, updating Magerun 1 next.

**Comment by mgeoffray** [comment]
@ktomk Pleasure to contribute !
Yes I will take a look and ask homebrew guys if that is possible this can be a very good addition.
I keep you informed about that.
Thank you for your work !

**Pull request merged**
