### PR TITLE
Add Magento CE 2.0.7

### PR DESCRIPTION
**Pull request by diazwatson**
- Add Magento CE 2.0.7 to install options

### CODE REVIEW

**Comment by cmuench** [comment]
Thanks. Can you exclude the new version in travis file for PHP 5.5?
Since 2.1 Magento needs at least PHP 5.6.

**Comment by diazwatson** [comment]
Hi Christian, could you please confirm that the changes are correct?
I am afraid, I am not really a travis expert :(

**Comment by cmuench** [comment]
@diazwatson Thanks. It's all good.

**Comment by diazwatson** [comment]
Cool :dancer:

**Pull request merged**
