### PR TITLE
Simple Version update for Magento 2.2

### PR DESCRIPTION
**Pull request by atlan**
Do not degrade Symfony YAML component when installing Magerun 2 w/ latest Magento 2.2 via Composer.

There is an incompatibility with the YAML format when Symfony YAML 3.x is used ("@" use in non-quoted scalars - e.g. for table-groups in Magerun config files, since ca. 2005 per YAML specs). As the Magerun project didn't communicate this non-standard use of the reserved notation earlier, Magerun users who write their own table-groups need to be made aware of this.

- [ ] Blog-post on magerun.net about the issue
- [ ] Add composer installations of the source version of Magerun  (1+2) into the Travis build
- [ ] Update version constraints w/ a Magerun version that shows a backwards incompatible change.

### CODE REVIEW

**Comment by ktomk** [comment]
@atlan: Could you please outline what the error message was you got? And have you checked this as well against older Magento 2 versions? It might be necessary to allow the old and new version (e.g. [logical OR](https://getcomposer.org/doc/articles/versions.md#version-range) ).

**Comment by hostep** [comment]
@atlan: you can install n98/magerun2 on Magento 2.2.0, but it will downgrade both `symfony/dependency-injection` and `symfony/config` to a lower version.

Let me demonstrate on a freshly installed Magento 2.2.0 project using composer:
```
$ composer require n98/magerun2
Using version ^1.6 for n98/magerun2
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for n98/magerun2 ^1.6 -> satisfiable by n98/magerun2[1.6.0].
    - Conclusion: remove symfony/dependency-injection v3.3.9
    - Conclusion: don't install symfony/dependency-injection v3.3.9
...

# this isn't working, because composer isn't trying hard enough to find compatible dependencies
# let's try this again...

$ composer require --no-update n98/magerun2
Using version ^1.6 for n98/magerun2
./composer.json has been updated

$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 14 installs, 2 updates, 0 removals
  - Updating symfony/dependency-injection (v3.3.9 => v3.1.10): Loading from cache
  - Updating symfony/config (v3.3.9 => v3.2.13): Loading from cache
  - Installing pbergman/tree-helper (1.0): Loading from cache
  - Installing twig/twig (v1.35.0): Loading from cache
  - Installing symfony/yaml (v2.8.27): Loading from cache
  - Installing symfony/translation (v3.0.9): Loading from cache
  - Installing symfony/validator (v2.8.27): Loading from cache
  - Installing jakub-onderka/php-console-color (0.1): Loading from cache
  - Installing jakub-onderka/php-console-highlighter (v0.3.2): Loading from cache
  - Installing dnoegel/php-xdg-base-dir (0.1): Loading from cache
  - Installing nikic/php-parser (v3.1.1): Loading from cache
  - Installing symfony/var-dumper (v3.3.9): Downloading (100%)
  - Installing psy/psysh (v0.8.11): Loading from cache
  - Installing n98/junit-xml (1.0.0): Loading from cache
  - Installing fzaninotto/faker (v1.7.1): Loading from cache
  - Installing n98/magerun2 (1.6.0): Loading from cache
```

So, if you do a `require --no-update` followed by a `update` it will work.
But watch the first two lines, it downgrades `symfony/dependency-injection` and `symfony/config` to a lower version.

Changing the dependency of `symfony/yaml` to `^3.0` is also going to solve the issue, and that's because `symfony/dependency-injection` version `3.3.9` has a [conflict defined](https://github.com/magento/magento2/blob/2.2.0/composer.lock#L5612) with `symfony/yaml` packages lower then version `3.3.0`.

I hope this helps.

@ktomk: it might be worth looking into making n98/magerun2 compatible with higher versions of those symfony packages, I don't really like it when packages get downgraded by installing another package. Reminds me of https://github.com/netz98/n98-magerun2/issues/234

If you decide to increase the versions of the symfony dependencies, please see if there is nothing in use of those dependencies which behaves differently between the old and newer version. The fact that `symfony/dependency-injection` defines a known conflict in its dependencies, already has me worried about such a thing.

But I'll leave it up to you to see can be done here.

**Comment by ktomk** [comment]
@hostep: I'm open here to actually find a good working requirement. We use console and finder as main components in Magerun IIRC. I don't think dependency injection actually is in use, maybe some of the subsystems then use it.

I also don't like to have downgrade constraints. My earlier suggestion in a comment above was to allow both (via logical OR). I remember the issue you referenced. That time the decision was to pin it to the lower version(s) IIRC. That at least made it stable.

What about adding a *install magerun via composer* to the Travis suite? So we can test it against all the different Magento versions. That should give a better experience to those users who install it via composer. 

This should be feasible with a VCS repositorie and the `file://` protocol even against the source version. It's some time ago I tried this with composer, bit that time it worked and from what I know this is supported.

**Comment by ktomk** [comment]
/e: And re-reading, we might have conflicts here b/c Magerun also requires Composer, this is used in the setup command IIRC. Composer then again uses Symfony components, again Console.

**Comment by hostep** [comment]
@ktomk: I think the problem is the `symfony/yaml` component here, the others are much less relevant I think.
I agree that the constraint can be changed to `^2.3 || ^3.0` but it will need to be tested to see if upgrading to version 3.x.x isn't going to cause problems in the code that Magerun uses from `symfony/yaml`

Testing magerun by installing it through composer in all supported Magento versions is a good idea, since it will probably use different versions of dependencies then if you test it stand-alone.

**Comment by ktomk** [comment]
@hostep: Yes, YAML, you mentioned it earlier already I remember. In Magerun this is mainly for config parsing IIRC, which is pretty straight forward. Just in case, we can bridge it if there are differences between the versions. AFAIK we don't use the new features in the v3 YAML component so this should be good in both ways. Composer does not use YAML IIRC, so this should be fine, too.

**Comment by atlan** [comment]
With the logical OR it works in older Versions too

**Comment by hostep** [comment]
Nice find @atlan!
So it looks like the upgrade to 3.3.x of `symfony/yaml` _does_ have some consequences.

According to the [yaml spec](http://www.yaml.org/spec/1.2/spec.html), the `@` and `` ` `` characters are reserved. And the [`symfony/yaml` changelog](https://github.com/symfony/yaml/blob/master/CHANGELOG.md) says (for version 2.8):
> Deprecated usage of @, `, | and > at the beginning of an unquoted string

So the solution seems to be to quote them with either single or double qoutes, so if you replace it with: `tables: '@log @session'` it should probably work?

@ktomk: does this break backwards compatibility? According to the [magerun1 wiki](https://github.com/netz98/n98-magerun/wiki/Stripped-Database-Dumps#add-your-own-groups) you can define your own tables. So if that's the case, then it might cause trouble if users update to a newer version of n98/magerun2 where this gets fixed.

**Comment by ktomk** [comment]
Well, it then requires us to quote these strings which should not be a problem, no deal-breaker. Just quote these strings (white-space separated table-names or table-group-names). This is also backwards compatible, older YAML parser versions should work fine with quoted strings. Just some more bytes in the config to have it properly encoded.

@atlan: Feel free to quote those strings in the config. For consistency I think all the `tables` entries should be quoted with single quotes, as we don't need further character escapes (like `\n` for newline).

Refs:

- YAML 1.2 - Example 2.17. Quoted Scalars http://www.yaml.org/spec/1.2/spec.html#id2761268

- YAML 1.1 - Example 2.17. Quoted Scalars http://yaml.org/spec/1.1/#id858553

I can file an according change to Magerun 1

**Comment by atlan** [comment]
@ktomk 
Ok, did some quoting ;) It now starts without errors. Please check ;)

**Comment by ktomk** [comment]
@atlan: Thanks, I also already filed a change against Magerun 1, see https://github.com/ktomk/n98-magerun/commit/2a6eb6fdac36bf6a4a5c1431c4817ec261b90c51 , currently on my own repo to see what Travis says: https://travis-ci.org/ktomk/n98-magerun/builds/282939076

**Comment by hostep** [comment]
@ktomk: the reason why I'm worried about backwards compatibility issues, is that certain users might have defined their own `tables` in their own config files, so if they update to a newer version of magerun2 which comes with a newer version of `symfony/yaml` it will break their setup.

That's why I think this needs to be at least very good communicated, that users will have to update their config file when they use `@` characters when upgrading to a new version.

**Comment by ktomk** [comment]
Is the deprecation actually preventing the parsing? If not, this still would be backwards compatible. But yes, communication should be as clear and good as it gets.

Just pushed the changes to Magerun 1 and edited the Wiki page so that the given examples use quotes, too.

**Comment by hostep** [comment]
@ktomk: I'm assuming it fails parsing since that's what @atlan says.

The deprecation started in `symfony/yaml` 2.8, but the parsing works fine in 2.8, because that's the version which gets installed when you install magerun2 on Magento 2.1.x and there are no issues over there.
I'm assuming that it starts failing with version 3.0.0 of `symfony/yaml`, unfortunately the [changelog](https://github.com/symfony/yaml/blob/master/CHANGELOG.md) is really empty for version 3.0.0, but looking at the [source code changes](https://github.com/symfony/yaml/compare/v2.8.0...v3.0.0#diff-e77b17fcf1195b394d17e3fb6090e427), it seems to indicate it started throwing this error in version 3.0.0.

**Comment by ktomk** [comment]
Just checked, deprecation error since 2.8, exception since 3.0. So this is a show stopper.

Any idea how to communicate this properly? After this change this will fail on 2.2, but backwards compatibility is important ... .

**Comment by hostep** [comment]
@ktomk: just for clarification: right now there isn't any issue on Magento 2.2.x, you just have to install it with composer using `composer require --no-update n98/magerun2 && composer update`, so it's not as "easy" to get it installed, but it should work perfectly fine. `symfony/yaml` version will be 2.8.27 (at this time), so there is no issue here.

You could choose to leave it like this.
The downside is, that n98/magerun2 will start running behind with its dependencies, this might be fine for the short term, but in the long term and with newer versions of Magento 2 I think there will be issues if n98/magerun2 still uses outdated dependency versions.

If you increase the dependency to version 3.0 of `symfony/yaml`, you will have to communicate this properly, definitly in the changelog, maybe also on http://magerun.net/ in a blog post detailing this.
If you want to do it properly, you should increase the major version as to indicate this is a backwards incompatible release, according to [semver.org](http://semver.org/)

It's possible that by upgrading the dependency to 3.0 it will no longer be possible to install the latest version of n98/magerun2 on Magento 2.0.x or 2.1.x, but that's something that you'll need to test. So it might mean that people on those versions will get stuck with the current latest version and will only be able to upgrade to a newer version of n98/magerun2 when they upgrade Magento to 2.2.x 
You could choose to maintain 2 different major versions of n98/magerun2 to combat this, but this means a lot of merging of fixes in two different branches, and will probably be really tedious to maintain.
(I'm not saying this scenario is correct, because I haven't verified this, this is just in theory).

I thinks it's best if you create a test branch with the constraints of `symfony/yaml` changed  (or use the PR branch from @atlan) and try to install it on a couple of different Magento versions and see what happens?

Just my thoughts, might be incorrect here and there, quickly typing this out, not testing anything, not good :p

**Comment by ktomk** [comment]
First of all I think we should offer an upgrade path to users. So far it looks like we have things together for that, the solution is quoting the skalars in the YAML file that start with "@" (which are table groups in specific).

I like the idea to have a blog-post about that so that we can increase awareness for Magerun users, giving a good direction on how to handle things safely. I can imagine many of our users are not aware of the deprecation (even this actually is old material in terms of the YAML standard). And to be precise, technically this is an oversight of our own (we could perhaps blame the half-ready YAML implementation in the Symfony parser ;), but in the end the MIT disclaimer reminds us that there was no fitness for a particular purpose ;) ++).

The line-up of composer commands is useful for interim purposes - and good to know  - but I would consider that a workaround. As well a workaround if we pin the lower version.

You suggestion to rely on semantic version sounds sane. We know there is a backwards incompatibility so we should raise the version number when we introduce that change (blog-post first so that we can reference it for upgraders).

The Travis build should be extended with a job for installation of Magerun w/ Composer against the Magento versions we have in the build, this is also a TODO. This should give use more confidence for composer installations with Magerun which should be well supported (IMHO). So this is something again we can do to improve. I can give it a try on my own fork (this is normally more practical for Travis modification than in a PR), but everybody else can try as well. This needs some experimenting and I yet do not see when I will find some time to give it a try.

The PR can then be rebased on top of the new testsuite when we get it ready. This should be a good path into future releases.

I don't like to keep multiple release branches for Magerun, as this is has a lot of overhead and is error prone. This will also produce more indirect feedback for errors etc, and esp. for the actual problem highlighted with this PR, I think it is feasible when upgraders update their config YAML files (the change is more or less straight forward, @atlan did it quickly in this PR and I did the changes yesterday for Magerun 1 in minutes - as we're just mortals, I'm pretty sure other Magerun users can do as well ;))

Good feedback @hostep, even if we still have some guesses, I'm sure this is already pretty well thought out. Just my 2 cents, but with updates on the Travis build we should have good coverage.

I'll update the TODO for this PR.

(note to myself: [Travis Build Stages (Beta)](https://docs.travis-ci.com/user/build-stages/))

**Comment by hostep** [comment]
Hi guys

Any chance this PR can get processed?
This turns out to be a real problem on the Magento Cloud environment.

Let me explain. Magento Cloud uses an extra composer package called `magento/ece-tools`, this package has recently introduced a dependency on `symfony/yaml` with the constraint: `^3.3`, so this means we can no longer update this package to the latest version since it conflicts with `n98/magerun2` dependency on `symfony/yaml` with constraint `~2.3`.

Merging this PR would most likely fix this problem.
Unfortunately this PR didn't make it in version 2.0 of magerun2, and since it might introduce backwards incompatible issues (already explained above), it might be necessary to create a version 3.0 once this PR is merged?

I think I will stop installing `n98/magerun2` using composer now in the Magento Cloud project and switch back to including the phar file in our git repo, which means we have to manually check for updates and can't rely on composer anymore for this unfortunately, but that's the short time fix, I hope once this PR gets processed we can switch back to using composer for magerun2.

Thanks!

**Comment by cmuench** [comment]
@hostep Could be a good idea to push n98-magerun2 to the phive project.

https://github.com/phar-io/phive

**Comment by hostep** [comment]
@cmuench: yes indeed, you reminded me of this ticket btw: https://github.com/netz98/n98-magerun2/issues/287 :)
Dependency issues are becoming more and more a problem in the Magento2 world as of lately with all the different versions out and all the different dependencies in all those Magento2 versions. Might not be a bad idea to start looking into Phive.

**Comment by cmuench** [comment]
@hostep I added support for phive. Hope it will be merged. See #287

**Comment by cmuench** [comment]
@hostep It is merged and running.

**Comment by cmuench** [comment]
I will close this PR. We can discuss this topic here, but the current PR is not valid anymore.

**Comment by hostep** [comment]
@cmuench : are there still plans to support `symfony/yaml` v3.x or higher?

I tested the phive solution a while ago, but I don't like it, I still prefer to just use composer to install magerun2 in a Magento2 project.

**Comment by cmuench** [comment]
@hostep At the moment I face the problem that Magento is upgrading all Symfony dependencies for Magento 2.3.
One of the main ideas of n98-magerun is that we need only one tool to manage multiple Magento versions. The composer installation is not the prefered way.
I am not sure if we can provide compatible n98-magerun versions for all old Magento versions in the future.
@fooman already created the issue #376.
At the moment I am investigating different options. If you have a good idea, let me know.

**Comment by hostep** [comment]
You could greate a new major version which is only compatible with Magento 2.3, and still maintain the older version with bugfixes which will only be compatible with Magento 2.0 - 2.2.
But that will probably mean that you have to do double work. So maybe it's not the best solution?

**Comment by cmuench** [comment]
Yes from "composer approach". But if you work for an agency or an hosting company and have multiple Magento versions to maintain, the phar file matches better. Maybe you are not allowed to modify the installation. 
In this case we have two phar files. I am not a fan of this.

**Comment by hostep** [comment]
Ok, it's certainly not a dealbreaker for us, we can just include the `.phar` file in vcs instead of installing it through composer per project.

This will keeps everything easier for you guys to maintain.

**Comment by cmuench** [comment]
@hostep I already thought about creating deb and rpm files for Linux installations. What do you mean?

**Pull request closed without merging**
