### PR TITLE
Add encrypt and decrypt commands

### PR DESCRIPTION
**Pull request by indykoning**
Magerun pull-request check-list:

- [x] Pull request against develop branch (if not, just close and create a new one against it)
- [x] README.md reflects changes (if any)
- [x] phar fuctional test (in tests/phar-test.sh)

Summary: (some words as summary)

Added an encrypt and decrypt command to easily debug encrypted values, and even be able to update encrypted value

### CODE REVIEW

**Comment by cmuench** [comment]
@indykoning Thanks. That's a nice addition for the dev commands. I wll review that next week.

**Comment by indykoning** [comment]
Sounds good!
I apologise for the lack of tests added as i do not know how to achieve consistent crypt_keys in your test workflow so the assertions are actually correct.

**Comment by cmuench** [comment]
@indykoning Idea for a test: Create a bats tests which calls the first `dev:encrypt` command with `foo` and then use the result to call the `dev:decrypt` command to test if the result is `foo` again.

**Comment by indykoning** [comment]
Good idea! It seems i have them working now. Feel free to review when you have the time

**Comment by cmuench** [comment]
@indykoning looks good for me. Merged.
Thanks!

**Pull request merged**
