### PR TITLE
Porting command eav:attribute:remove, tasks #100

### PR DESCRIPTION
**Pull request by jthln**
Porting command eav:attribute:remove, tasks #100

### CODE REVIEW

**Comment by jthln** [comment]
Issues with usage of `eavSetupFactory` in production mode and CE >= 2.0.6.

I'll have a look into that if I get some spare time.

**Comment by jthln** [comment]
Having another good look at it, I changed my mind.

I think, it's more safe, to _not_ offer a `eav:attribute:remove` command in **production** mode at all. 

Will commit changes accordingly.

**Comment by cmuench** [comment]
@jthln Thanks for contributing. Could you fix the production mode problems for M2 < 2.0.6?

**Comment by cmuench** [comment]
Thanks

**Pull request merged**
