### PR TITLE
Add Magento CE 2.0.3 and 2.0.5

### PR DESCRIPTION
**Pull request by diazwatson**
Changes proposed in this pull request:

- Add Magento CE 2.0.5

- Add Magento CE 2.0.3

### CODE REVIEW

**Comment by ktomk** [comment]
@diazwatson: Thanks! Last time I left 2.0.3 out because it was immediately superseded by 2.0.4. Was there a special reason why you took it in or just for completeness?

**Comment by ktomk** [comment]
CE 2.0.5 is now part of 1.1.7, I remove 2.0.3 for the moment until this is specifically requested.

**Comment by diazwatson** [comment]
Hi @ktomk, sorry it was just for completeness as you said.

**Comment by ktomk** [comment]
Hey @diazwatson, no problem at all. Thank you for the quick PR, 2.0.5 is out pretty short.

**Comment by diazwatson** [comment]
Glad to help :-)
Btw I also noticed that the stability of the versions is declared as "alpha" and "beta" but could not find any reference of it in repository. How you know which is the current status?

**Comment by ktomk** [comment]
You can find that in the magento repository, it is in the composer.json file, the minimum-stability setting. IIRC this is because magento still has the alpha composer requirement. Hence the minimum-stability is alpha then, it's set internally so that the installation is possible. By default only stable packages are installed via composer.

Good you mention it, magento could switch to the now stable version of composer, so the alpha minimum stability wouldn't be a requirement any longer. I just quickly opened an issue over there: https://github.com/magento/magento2/issues/4359 .

**Comment by diazwatson** [comment]
@ktomk forgot to thank you for the explanation :)

**Comment by ktomk** [comment]
@diazwatson You're welcome!

**Pull request merged**
