### PR TITLE
Generate a shorter version of registration.php

### PR DESCRIPTION
**Pull request by Zifius**
Magerun pull-request check-list:

- [x] Pull request against develop branch (if not, just close and create a new one against it)
- [x] README.md reflects changes (if any)

Subject: Generate a shorter version of registration.php

Changes proposed in this pull request:

- Made registration.php a bit shorter and more readable by use-ing namespace

### CODE REVIEW

**Comment by tkn98** [comment]
Thanks for your PR. We have a guidleine to terminate all lines in text-files with the newline marker. This includes the last line. This conflicts with the first commit in the PR which changes diverse files to no newlines at the end of file. So these are not extra ending lines but just newlines at the end of file, which is intended and not considered an error (compare with [3.206 Line](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206) in POSIX/IEEE Std 1003.1-2008, 2016 Edition).

The other change is correct, the use clause is superfluous and should be removed.

If you may update the PR by removing 368e356 and keeping 2b7e3b2? That would be great for a straight forward merge.

**Comment by Zifius** [comment]
@tkn98 Thanks for the feedback Tom, should the xml files also contain a new line in the end of files? Currently only module.xml.twig has it while other files in etc folder do not

> The other change is correct, the use clause is superfluous and should be removed.

Not sure I follow, I'm actually adding the use statement here to avoid using FQ namespace twice

**Comment by tkn98** [comment]
@Zifius: You're totally right,  I meant the "as" of the use clause which is superfluous, not the use clause itself as I wrote.

Can you ammend the PR and remove the first and last commit (the in + revert) and then force-push? That would be great then I can merge it directly, otherwise I would need to squash my own.

**Comment by Zifius** [comment]
@tkn98 Sure thing, but please give me feedback on the etc/*.xml files so that I don't push more commits after squashing

**Comment by tkn98** [comment]
Yes XML files are also of the text type and should contain these, too.

Btw. some more practical background about these newline characters: this allows to put multiple files after each other into a stream w/o loosing the information where the last line ended. This makes such files much more compatible with various text-tools.

Sorry that this was not so clear upfront that we have this for all text-files.

**Comment by Zifius** [comment]
Thanks @tkn98, I squashed the commits and added some missing new lines. Ready for your review

**Comment by tkn98** [comment]
Thanks!

**Comment by Zifius** [comment]
Cheers @tkn98!

**Pull request merged**
