### PR TITLE
Help description of system:setup:compare-versions

### PR DESCRIPTION
**Pull request by p-makowski**
Fixes help description of "system:setup:compare-versions"

### CODE REVIEW

**Comment by p-makowski** [comment]
> phpunit
PHP Parse error:  syntax error, unexpected '[' in /home/ubuntu/n98-magerun2/dev/tests/N98/Magento/Command/System/InfoCommandTest.php on line 45
phpunit returned exit code 255

Seems like this check should be executed in PHP 5.4+  (https://wiki.php.net/rfc/shortsyntaxforarrays)

**Comment by tkn98** [comment]
@p-makowski: FYI: Magento 2.0.early requires PHP 5.4+ at least.

**Comment by tkn98** [comment]
We believe that the issue reported is taken care of in the development version. It can be upgraded to it using the self-update command with the --unstable switch.

**Comment by tkn98** [comment]
Thanks!

**Pull request closed without merging**
