### PR TITLE
Adding argument --include to command db:dump

### PR DESCRIPTION
**Pull request by hannes011**
Magerun pull-request check-list:

- [x] Pull request against develop branch (if not, just close and create a new one against it)
- [x] README.md reflects changes (if any)

Subject: Adding argument --include to command db:dump

Fixes # .

Changes proposed in this pull request:

- Expanding command db:dump by adding argument --include to existing argument --exclude

### CODE REVIEW

**Comment by cmuench** [comment]
@hannes011 Thanks for the PR.
There is a small code violation in the class `DumpCommandTest`.
Can you remove the blank line 188. That should fix the violation. Then we can see if the unit tests are fine.

**Comment by hannes011** [comment]
@cmuench I've removed the blank line
However, there are two more violations which appear to not be produced by me:
   1) src/N98/Magento/Command/Admin/User/ChangeStatusCommand.php
   2) src/N98/Magento/Command/Cms/ToggleBlockCommand.php

```
diff --git a/src/N98/Magento/Command/Admin/User/ChangeStatusCommand.php b/src/N98/Magento/Command/Admin/User/ChangeStatusCommand.php
index 9820a97..415342c 100644
--- a/src/N98/Magento/Command/Admin/User/ChangeStatusCommand.php
+++ b/src/N98/Magento/Command/Admin/User/ChangeStatusCommand.php
@@ -4,18 +4,18 @@ declare(strict_types=1);
 
 namespace N98\Magento\Command\Admin\User;
 
-use Magento\User\Model\User;
+use function is_string;
 use Magento\User\Model\ResourceModel\User as UserResourceModel;
 use Magento\User\Model\ResourceModel\User\CollectionFactory;
+use Magento\User\Model\User;
 use N98\Magento\Command\AbstractMagentoCommand;
+use function sprintf;
 use Symfony\Component\Console\Input\InputArgument;
 use Symfony\Component\Console\Input\InputInterface;
+
 use Symfony\Component\Console\Input\InputOption;
 use Symfony\Component\Console\Output\OutputInterface;
 
-use function is_string;
-use function sprintf;
-
 /**
  * Class ToggleBlockCommand
  * @package N98\Magento\Command\Admin\User
@@ -28,13 +28,13 @@ class ChangeStatusCommand extends AbstractMagentoCommand
 
     protected $userResourceModel;
     protected $userCollectionFactory;
-    
+
     public function inject(UserResourceModel $userResourceModel, CollectionFactory $userCollectionFactory): void
     {
         $this->userResourceModel = $userResourceModel;
         $this->userCollectionFactory = $userCollectionFactory;
     }
-    
+
     protected function configure(): void
     {
         $this
@@ -99,7 +99,7 @@ class ChangeStatusCommand extends AbstractMagentoCommand
             return true;
         }
 
-        if($input->getOption(self::DEACTIVATE_OPTION) === true) {
+        if ($input->getOption(self::DEACTIVATE_OPTION) === true) {
             return false;
         }
 
diff --git a/src/N98/Magento/Command/Cms/ToggleBlockCommand.php b/src/N98/Magento/Command/Cms/ToggleBlockCommand.php
index 925b37e..02c9ed7 100644
--- a/src/N98/Magento/Command/Cms/ToggleBlockCommand.php
+++ b/src/N98/Magento/Command/Cms/ToggleBlockCommand.php
@@ -4,17 +4,17 @@ declare(strict_types=1);
 
 namespace N98\Magento\Command\Cms;
 
+use function is_string;
 use Magento\Cms\Api\BlockRepositoryInterface;
-use Magento\Framework\Exception\NoSuchEntityException;
 use Magento\Framework\Exception\LocalizedException;
+use Magento\Framework\Exception\NoSuchEntityException;
 use N98\Magento\Command\AbstractMagentoCommand;
+use function sprintf;
 use Symfony\Component\Console\Input\InputArgument;
+
 use Symfony\Component\Console\Input\InputInterface;
 use Symfony\Component\Console\Output\OutputInterface;
 
-use function is_string;
-use function sprintf;
-
 /**
  * Class ToggleBlockCommand
  * @package N98\Magento\Command\Cms
```

**Comment by cmuench** [comment]
@hannes011 That code standard violations were already fixed in the develop branch. Can you rebase?
We switched to Github actions last week. Your PR is the first one after the migration.
Seems that there is also a config problem with the markeplace tokens. I updates the workflow in the develop branch. Hopefully that will work then.

**Comment by hannes011** [comment]
@cmuench rebase done

**Comment by cmuench** [comment]
@hannes011 it's not a rebase. You did a merge.

**Comment by hannes011** [comment]
@cmuench sorry - my mistake... removed my last commit and made a proper rebase

**Comment by cmuench** [comment]
@hannes011 merged :-)

**Pull request merged**
