### PR TITLE
Add workflow to create a github release

### PR DESCRIPTION
**Pull request by cmuench**
Changes proposed in this pull request:

- Remove separate release workflow file
- Add new job in release workflow which creates a github release with attached n98-magerun2.phar and gpg sign file.

### CODE REVIEW

**Comment by cmuench** [comment]
Related to #1098

@drupol I changed the release workflow to Github Actions to provide more tranparency.
The new workflow will publish the phar file to files.magerun.net and additionally as Github Release.
The updater of n98-magerun will still use the files.magerun.net site to download updates.
If someone want to use Github as download resource, it's then possible.

**Comment by drupol** [comment]
Amazing stuff ! Thank you very much for this, I'll update the packages in nixpkgs in the upcoming days.

Why did you suddenly change your mind about it ?

**Comment by cmuench** [comment]
@drupol I thought it's important to increase the "truck count".
I am the only guy who understands the deployment.
Transparency of an open source project is also important.

**Comment by cmuench** [comment]
@drupol If you change the nix package... Please orient on the last release 7.1.0.
The package will always contain a n98-magerun2.phar and a n98-magerun2.phar.asc with the detached GPG Signaturen.

I also attached the corresponding phar files to older release. Older releases have the tag in the phar. That will not be happen for upcoming releases.

**Comment by drupol** [comment]
Cool ! 

Created the PR: https://github.com/NixOS/nixpkgs/pull/252905

**Comment by drupol** [comment]
Done. I've updated both `n98-magerun` and `n98-magerun2`, now using Github as primary source.

I noticed that there's a difference in the URL pattern between the two, I've adapted the code. If by any chance you could align both pattern, ping me, and I'll do the changes in `nixpkgs`.

**Comment by cmuench** [comment]
@drupol The latest release was wrong for n98-magerun (v1).
This is now the latest release: https://github.com/netz98/n98-magerun/releases/tag/2.3.0

I was able to change the file name as well.

**Comment by drupol** [comment]
Done, I just pushed the PR to change the URL. Thanks!

**Pull request merged**
